name = "PoissonDiskSampling"
uuid = "d57be0ce-7c7e-4f32-9a47-3bfb603400bb"
authors = ["Keita Nakamura <keita.nakamura.1109@gmail.com>"]
version = "0.3.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
